# Generated by Django 5.2.1 on 2025-06-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_style', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningCharacteristic',
        ),
    ]
