# Generated by Django 5.2.1 on 2025-06-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_style', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
